name: TimeSync
version: '1.2'
main: de.elnino0916.TimeSync.TimeSync
api-version: '1.20'
author: elNino0916
description: Syncs the real time with your worlds.
website: https://github.com/elNino0916/TimeSyncPlugin