sync-interval: 20  # Sync interval in ticks (20 ticks = 1 second)
worlds:
  world:
    enabled: true
    timezone: "Europe/Berlin"
  world_nether:
    enabled: false
    timezone: "Europe/Berlin"
  world_the_end:
    enabled: false
    timezone: "Europe/Berlin"
  # Add worlds if needed
